### ISSUE TITLE
这个扩展好像被ScratchAddons收录了

### ISSUE THREAD

**Issue by BananaCakeComputer** [summerscar/scratchblocks2svg#4]
<img width="1440" alt="截屏2021-06-24 上午9 58 32" src="https://user-images.githubusercontent.com/77569325/123190768-c350b880-d4d2-11eb-919b-e074630c306e.png">

**Comment by summerscar** [comment]
是的  我前段时间向scratchaddon提交了pr

**Comment by summerscar** [comment]
@BananaCakeComputer  我很好奇你与Codemao之间发生了什么 :joy:
